name: Build Android APK

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Expo CLI
        run: npm install -g expo-cli

      - name: Install Dependencies
        run: npm install

      - name: Login to Expo
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
        run: expo login --token $EXPO_TOKEN

      - name: Build APK
        run: expo build:android -t apk

      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: hyperxgen-apk
          path: dist/*.apk
